### ISSUE TITLE
CommonJS support

### ISSUE THREAD

**Issue by SaltyAom** [bogeychan/elysia-polyfills#1]
[Elysia 0.5 add support for CommonJS](https://elysiajs.com/blog/elysia-05.html#notable-improvement) by default, this should allow us to drop the additional step of using CLI to convert Elysia modules to CommonJS.

It would be nice if would you updated the package to support CommonJS as well.

**Comment by bogeychan** [comment]
Sounds good, I will give it a try.

But I think since you introduced code analysis, it won't work without a build step (before each run) because of bun transpile step, for example:

[isFnUse](https://github.com/elysiajs/elysia/blob/08a4375b91d9d359fe7a0264b29d7512a729ea8f/src/compose.ts#L73)

```js
// Bun
let is = isFnUse(
  'set',
  `(context) => {
    if (handleOrigin(context.set, context.request), handleMethod(context.set), exposedHeaders.length)
      context.set.headers["Access-Control-Allow-Headers"] = typeof allowedHeaders === "string" ? allowedHeaders : allowedHeaders.join(", ");
    if (maxAge)
      context.set.headers["Access-Control-Max-Age"] = maxAge.toString();
    return new Response("", {
      status: 204
    });
  }`
);

console.log(is); // true

// Node
is = isFnUse(
  'set',
  `context => {
        handleOrigin(context.set, context.request);
        handleMethod(context.set);
        if (exposedHeaders.length) context.set.headers['Access-Control-Allow-Headers'] = typeof allowedHeaders === 'string' ? allowedHeaders : allowedHeaders.join(', ');
        if (maxAge) context.set.headers['Access-Control-Max-Age'] = maxAge.toString();
        return new Response('', {
          status: 204
        });
      }`
);

console.log(is); // false
```

bugs in `Bun.build` / `bun build` kinda blocks progress atm

**Comment by bogeychan** [comment]
I got it working without using `Bun.build`. I adjusted the following parts of [isFnUse](https://github.com/elysiajs/elysia/blob/08a4375b91d9d359fe7a0264b29d7512a729ea8f/src/compose.ts#L73), in case you encounter the same problem in the future with `bun`.

https://github.com/bogeychan/elysia-polyfills/blob/302cceaea8feb06aa701b166fb362678f828af3a/scripts/runtime.js#L38-L46

https://github.com/bogeychan/elysia-polyfills/blob/302cceaea8feb06aa701b166fb362678f828af3a/scripts/runtime.js#L51-L57

I'll look into CommonJS support tomorrow

**Comment by bogeychan** [comment]
CommonJS support should be added without build-step in `@bogeychan/elysia-polyfills@0.5.1` and `create-elysia@0.0.15`:

```bash
yarn create elysia my-elysia-app --template node
```

If you want to support ESM hybrid with CJS in Elysia you can follow [this blog post](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html). I implemented the same approach.

Furthermore you have to use `"moduleResolution": "nodenext"`, (i.e. specify all imports and exports with `.js` extension)
