### ISSUE TITLE
TypeError: this.server.reload is not a function

### ISSUE THREAD

**Issue by dtinth** [bogeychan/elysia-polyfills#2]
Elysia calls `this.server.reload()` here whenever `.use()` is called:

https://github.com/elysiajs/elysia/blob/9192fa90c57467a3f60fe6c5e8963e89a994a2bc/src/index.ts#L2716

This results in this runtime error:

```
TypeError: this.server.reload is not a function
    at Elysia.compile (node_modules/elysia/dist/cjs/index.js:518:25)
```

## Workaround

I worked around this issue from the userland by monkey-patching `Bun.server` to add a no-op `.reload()` function to the server instance.

```ts
import '@bogeychan/elysia-polyfills/node/index.js'

const originalServe = globalThis.Bun.serve

// Implement server.reload() function. Otherwise, Elysia may crash with:
//
// TypeError: this.server.reload is not a function
//     at Elysia.compile (node_modules/elysia/dist/cjs/index.js:518:25)
//
globalThis.Bun.serve = function (...args) {
    const server = originalServe.apply(this, args as any)
    if (!server.reload) {
        server.reload = () => {}
    }
    return server
}
```

**Comment by bogeychan** [comment]
Hi, thanks for your feedback! Should be fixed in version `0.6.0`.

Let me know if there is anything else.
